version: "3"

services:
  node:
    image: node:18-alpine
    volumes:
      - .:/code:cached
    working_dir: /code

  serverless:
    image: amaysim/serverless:3.35.2
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file: .env
