services:
  node:
    image: node:20-alpine
    volumes:
      - .:/code:cached
    working_dir: /code

  serverless:
    image: amaysim/serverless:3.39.0
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file: .env
