service: typescript-serverless-template

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: ${env:AWS_DEPLOYMENT_BUCKET}
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript

functions:
  hello:
    handler: src/handlers/hello.handle
    timeout: 20
    memorySize: 128
    events:
      - httpApi:
          method: get
          path: /hello
    environment:
      GREET_WHO: ${env:GREET_WHO}
